# +-----------------------------+
# |  ゲーム設定 - Game Settings |
# +-----------------------------+

startCmd:
  countdown: 10

onDied:
  # 死亡時設定 - onDied Settings
  #   enabled: (Boolean)
  #     有効化するか?
  #   triggered: (String)
  #     プレイヤーがキルされれば何を実行するか
  #     > GAMEMODE
  #       ゲームモードを指定 (valueにゲームモードを記述)
  #     > COMMAND
  #       死んだらコマンドを実行 (valueにコマンドを記述)
  #   value: (String)
  #     上のtriggerdで指定したものによって変わります
  #     > 例:
  #       COMMAND -> give @a stick 1 -> 棒を一個全員に
  #       GAMEMODE -> SPECTATOR (他にADVENTURE / CREATIVE / SURVIVAL を指定できます。)
  enabled: false

  triggered: "GAMEMODE"
  value: "SPECTATOR"

# +-----------------------------+
# |  チーム設定 - Team Settings |
# +-----------------------------+

team_one:
  teleport: false
  x: 0
  y: 100
  z: 0

  id: red

  enable_cmd: false
  commands: [
    "give @a[team=red] stone_sword 1"
  ]

team_two:
  teleport: false
  x: 0
  y: 100
  z: 0

  id: blue

  enable_cmd: false
  commands: [
    "give @a[team=blue] stone_sword 1"
  ]

# +-----------------------------+
# |  翻訳設定 - trans. settings |
# +-----------------------------+

translate:
  start: "ゲーム開始"
  actionbar: "%online%人がオンライン / 赤チーム §c%TeamOne_online%§f 青チーム §9%TeamTwo_online%"
  prefix: "&b[&fNekoPvP&b] &f"
  reloaded: "設定ファイルを再読み込みしました。"